version: '3.8'
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unprotectedP@ssword
    volumes:
      - db_vol:/var/lib/mysql

  auth:
    build: ./auth
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: unprotectedP@ssword

  weather:
    build: ./weather
    restart: always
    environment:
      APIKEY: ################  Y O U R    A P I   K E Y  ##############

  ui:
    build: ./UI
    restart: always
    depends_on:
      - weather
      - auth
    ports:
      - 3000:3000
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
  
volumes:
  db_vol: